name: ci
 
on:
  push
 
jobs:
  ci:
    strategy:
      matrix:
        kind: ['windows', 'linux-mac']
        include:
          - kind: windows
            output: zip
            content: application/zip
          - kind: linux-mac
            output: tar.gz
            content: application/gzip
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      name: Checkout Code

    - name: Set variables
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Package it all up
      shell: bash
      run: cd profiles && if [ "${{ matrix.output }}" = "zip" ]; then 7z a -r -tzip ../out.zip *.md *.ini; else tar -czvf ../out.tar.gz *.md *.ini; fi 

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.vars.outputs.sha_short }}
        release_name: Release ${{ steps.vars.outputs.sha_short }}
        body: New release ${{ steps.vars.outputs.sha_short }}
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./out.${{ matrix.output }}
        asset_name: PrusaSlicer-3D-Filament-Profiles.${{ matrix.output }}
        asset_content_type: ${{ matrix.content }}
