name: ci
 
on:
  push
 
jobs:
  buildtest:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
      
    - name: Zip it all up
      shell: bash
      run: 7z a -r -tzip out.zip *.md *.ini

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: New release ${{ steps.vars.outputs.VERSION }}
        draft: false
        prerelease: false

    - name: Upload Release Assets
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./out.zip
        asset_name: PrusaSlicer-3D-Filament-Profiles.zip
        asset_content_type: application/zip
